/*
La table TA_VOIE_SUPRA_COMMUNALE_LOG rassemblant les informations de chaque voie et notamment leurs libellés et leur latéralité : une voie physique peut avoir deux noms différents (à gauche et à droite) si elle traverse deux communes différentes.
*/

-- 1. Création de la table TA_VOIE_SUPRA_COMMUNALE_LOG
CREATE TABLE G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE_LOG(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    id_voie NUMBER(38,0) NOT NULL,
    nom_voie VARCHAR2(100 BYTE) NOT NULL,
    date_action DATE,
    fid_type_action NUMBER(38,0)
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE_LOG IS 'Table de log de la table TA_VOIE_SUPRA_COMMUNALE permettant d''avoir l''historique de toutes les évolutions des voies supra-communales.';
COMMENT ON COLUMN G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE_LOG.objectid IS 'Clé primaire auto-incrémentée de la table.';
COMMENT ON COLUMN G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE_LOG.id_voie IS 'Champ contenant les identifiants des voies supra-communales de la table TA_VOIE_SUPRA_COMMUNALE.';
COMMENT ON COLUMN G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE_LOG.nom_voie IS 'Champ contenant les identifiants des voies supra-communales de la table SIREO_LEC.EXRD_ORDONNEE.';
COMMENT ON COLUMN G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE_LOG.date_action IS 'date de saisie, modification et suppression des voies supra-communales.';
COMMENT ON COLUMN G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE_LOG.fid_type_action IS 'Clé étrangère vers la table TA_LIBELLE permettant de catégoriser le type d''action effectué sur les voies supra-communales.';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE_LOG 
ADD CONSTRAINT TA_VOIE_SUPRA_COMMUNALE_LOG_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des clés étrangères
ALTER TABLE G_BASE_VOIE.TA_VOIE_ADMINISTRATIVE_LOG
ADD CONSTRAINT TA_VOIE_SUPRA_COMMUNALE_LOG_FID_TYPE_ACTION_FK
FOREIGN KEY (fid_type_action)
REFERENCES G_BASE_VOIE.TA_TYPE_VOIE(objectid);

-- 4. Création des index
CREATE INDEX TA_VOIE_SUPRA_COMMUNALE_LOG_ID_VOIE_IDX ON G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE_LOG(id_voie)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_VOIE_SUPRA_COMMUNALE_LOG_NOM_VOIE_IDX ON G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE_LOG(nom_voie)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_VOIE_SUPRA_COMMUNALE_LOG_DATE_ACTION_IDX ON G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE_LOG(date_action)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_VOIE_SUPRA_COMMUNALE_LOG_FID_TYPE_ACTION_IDX ON G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE_LOG(fid_type_action)
    TABLESPACE G_ADT_INDX;

-- 5. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE_LOG TO G_ADMIN_SIG;

/

