/*
Table TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE - du projet D de correction des noms de voies - matérialisant la géométrie des voies administratrives principales (c''est-à-dire qu''aucune voie secondaire n''est présente dans cette table).
*/

-- 1. Création de la table TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE
CREATE TABLE G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    libelle_voie VARCHAR2(1000 BYTE),
    complement_nom_voie VARCHAR2(200),
    code_insee VARCHAR2(5),
    date_saisie DATE,
    date_modification DATE,
    fid_pnom_saisie NUMBER(38,0),
    fid_pnom_modification NUMBER(38,0),
    fid_type_voie NUMBER(38,0),
    fid_etat NUMBER(38,0),
    geom  SDO_GEOMETRY NOT NULL
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE IS 'Table - du projet D de correction des noms de voies - matérialisant la géométrie des voies administratrives principales (c''est-à-dire qu''aucune voie secondaire n''est présente dans cette table).';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE.objectid IS 'Clé primaire auto-incrémentée de la table. Elle remplace l''ancien identifiant ccomvoie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE.libelle_voie IS 'Nom de voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE.complement_nom_voie IS 'Complément de nom de voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE.code_insee IS 'Code insee de la voie "administrative".';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE.date_saisie IS 'Date de création du libellé de voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE.date_modification IS 'Date de modification du libellé de voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE.fid_pnom_saisie IS 'Clé étrangère vers la table TEMP_D_AGENT indiquant le pnom de l''agent créateur du libellé de voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE.fid_pnom_modification IS 'Clé étrangère vers la table TEMP_D_AGENT indiquant le pnom de l''agent éditeur du libellé de voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE.fid_type_voie IS 'Clé étrangère vers la table TEMP_D_TYPE_VOIE permettant d''associer une voie à un type de voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE.fid_etat IS 'Clé étrangère vers la table TEMP_D_LIBELLE permettant d''identifier l''état d''avancement de la correction des noms de voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE.geom IS 'Géométrie de type multiligne de chaque voie administrative.';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE 
ADD CONSTRAINT TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);

-- 5. Création de l'index spatial sur le champ geom
CREATE INDEX TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE_SIDX
ON G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTILINE, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 6. Création des clés étrangères
ALTER TABLE G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE
ADD CONSTRAINT TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE_FID_PNOM_SAISIE_FK 
FOREIGN KEY (fid_pnom_saisie)
REFERENCES G_BASE_VOIE.TEMP_D_AGENT(numero_agent);

ALTER TABLE G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE
ADD CONSTRAINT TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE_FID_PNOM_MODIFICATION_FK
FOREIGN KEY (fid_pnom_modification)
REFERENCES G_BASE_VOIE.TEMP_D_AGENT(numero_agent);

ALTER TABLE G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE
ADD CONSTRAINT TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE_FID_TYPE_VOIE_FK
FOREIGN KEY (fid_type_voie)
REFERENCES G_BASE_VOIE.TEMP_D_TYPE_VOIE(objectid);

ALTER TABLE G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE
ADD CONSTRAINT TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE_FID_ETAT_FK
FOREIGN KEY (fid_etat)
REFERENCES G_BASE_VOIE.TEMP_D_LIBELLE(objectid);

-- 7. Création des index sur les clés étrangères et autres
CREATE INDEX TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE_FID_PNOM_SAISIE_IDX ON G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE(fid_pnom_saisie)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE_FID_PNOM_MODIFICATION_IDX ON G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE(fid_pnom_modification)
    TABLESPACE G_ADT_INDX;

-- 8. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_BASE_VOIE.TEMP_D_VOIE_ADMINISTRATIVE_PRINCIPALE TO G_ADMIN_SIG;

/

