/*
Table de log de la table TA_VOIE_PHYSIQUE permettant d''avoir l''historique de toutes les évolutions des voies physiques.
*/

-- 1. Création de la table TA_VOIE_PHYSIQUE_LOG
CREATE TABLE G_BASE_VOIE.TA_VOIE_PHYSIQUE_LOG(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    id_voie_physique NUMBER(38,0)
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_BASE_VOIE.TA_VOIE_PHYSIQUE_LOG IS 'Table de log de la table TA_VOIE_PHYSIQUE permettant d''avoir l''historique de toutes les évolutions des voies physiques.';
COMMENT ON COLUMN G_BASE_VOIE.TA_VOIE_PHYSIQUE_LOG.objectid IS 'Clé primaire auto-incrémentée de la table.';
COMMENT ON COLUMN G_BASE_VOIE.TA_VOIE_PHYSIQUE_LOG.id_voie_physique IS 'Identifiants des voies physiques de la table TA_VOIE_PHYSIQUE.';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TA_VOIE_PHYSIQUE_LOG 
ADD CONSTRAINT TA_VOIE_PHYSIQUE_LOG_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des index
CREATE INDEX TA_VOIE_PHYSIQUE_LOG_ID_VOIE_PHYSIQUE_IDX ON G_BASE_VOIE.TA_VOIE_PHYSIQUE_LOG(id_voie_physique)
    TABLESPACE G_ADT_INDX;

-- 6. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_BASE_VOIE.TA_VOIE_PHYSIQUE_LOG TO G_ADMIN_SIG;

/

