/*
La table TA_VOIE_SUPRA_COMMUNALE rassemblant les informations de chaque voie et notamment leurs libellés et leur latéralité : une voie physique peut avoir deux noms différents (à gauche et à droite) si elle traverse deux communes différentes.
*/

-- 1. Création de la table TA_VOIE_SUPRA_COMMUNALE
CREATE TABLE G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    nom_voie VARCHAR2(100 BYTE) NOT NULL,
    date_saisie DATE,
    date_modification DATE
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE IS 'Table rassemblant les informations de chaque voie et notamment leurs libellés et leur latéralité : une voie physique peut avoir deux noms différents (à gauche et à droite) si elle traverse deux communes différentes.';
COMMENT ON COLUMN G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE.objectid IS 'Clé primaire auto-incrémentée de la table.';
COMMENT ON COLUMN G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE.nom_voie IS 'Champ contenant les identifiants des voies supra-communales de la table SIREO_LEC.EXRD_ORDONNEE. Chaque insertion ou modification dans la table EXRD_ORDONNEE est répercutée dans la table TA_VOIE_SUPRA_COMMUNALE.';
COMMENT ON COLUMN G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE.date_saisie IS 'Date de saisie en base d''une voie supra-communale.';
COMMENT ON COLUMN G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE.date_modification IS 'Date de modification en base d''une voie supra-communale.';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE 
ADD CONSTRAINT TA_VOIE_SUPRA_COMMUNALE_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des index
CREATE INDEX TA_VOIE_SUPRA_COMMUNALE_NOM_VOIE_IDX ON G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE(nom_voie)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_VOIE_SUPRA_COMMUNALE_DATE_SAISIE_IDX ON G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE(date_saisie)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_VOIE_SUPRA_COMMUNALE_DATE_MODIFICATION_IDX ON G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE(date_modification)
    TABLESPACE G_ADT_INDX;

-- 5. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE TO G_ADMIN_SIG;

/

